version: '3'
services:
  selenium:
      image: selenium/hub:3.11.0-californium
      ports:
        - "4444:4444"
      environment:
        - GRID_TIMEOUT=0
        - GRID_DEBUG=true
      depends_on:
        - opencart
  chrome:
    image: selenium/node-chrome:3.11.0-californium
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=7
      - NODE_MAX_SESSION=7
      - SCREEN_WIDTH=1900
      - SCREEN_HEIGHT=1600
      - SCREEN_DEPTH=24
  firefox:
    image: selenium/node-firefox:3.11.0-californium
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - SCREEN_WIDTH=1900
      - SCREEN_HEIGHT=1600
      - SCREEN_DEPTH=24
  opencart-tests:
    build: .
    image: opencart-tests
    depends_on:
      - firefox
      - chrome
    volumes:
      - ./reports:/tests/target/allure-results